# Generated by Django 5.2.14 on 2026-08-31 02:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('file_name', models.CharField(blank=True, default='', max_length=500)),
                ('content_type', models.CharField(blank=True, default='', max_length=200)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', '待解析'), ('parsing', '解析中'), ('ready', '已就绪'), ('failed', '解析失败')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rag.knowledgebase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.document')),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.knowledgebase')),
            ],
            options={
                'ordering': ['document', 'index'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['kb', 'status'], name='rag_documen_kb_id_f86b37_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['kb'], name='rag_chunk_kb_id_c6f8a5_idx'),
        ),
    ]
